const actionsName = {
    CREATE_BLANK_BOARD: "CREATE_BLANK_BOARD",
    CREATE_STARTED_GAME_BOARD: 'CREATE_STARTED_GAME_BOARD',
    OPEN_CELL: "OPEN_CELL",
    RIGHT_CLICK_CELL: 'RIGHT_CLICK_CELL',
    CHANGE_LEVEL: 'CHANGE_LEVEL',
    GAME_OVER: 'GAME_OVER',
};

export default actionsName;